name       : whdd
homepage   : http://whdd.org/
version    : 3.0
release    : 1
source     :
    - https://github.com/whdd/whdd/archive/3.0.tar.gz : b0877375a54e0c915dfe418f5330b0e1d409629d1f298539f6a0556df2c8335a
license    : GPL-3.0
component  : system.utils
summary    : HDD diagnostic and data recovery tool for Linux
description: |
    WHDD is HDD diagnostic and recovery tool for Linux.
builddeps  :
    - dialog-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-libdevcheck-Fix-portability-issues-with-GNU-C.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
